# Generated by Django 5.1.2 on 2024-11-13 12:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energydata',
            name='current',
        ),
        migrations.RemoveField(
            model_name='energydata',
            name='power',
        ),
        migrations.RemoveField(
            model_name='energydata',
            name='voltage',
        ),
        migrations.AddField(
            model_name='energydata',
            name='energy_extra',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='energydata',
            name='energy_gen',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='energydata',
            name='energy_grid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='energydata',
            name='energy_meter',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='energydata',
            name='energy_self',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
