# Generated by Django 5.1.2 on 2024-11-05 21:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_energydata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
